
version: 2

sources:
    - name: staging
      #NOTE: you can take the following data from the query in BQ when you try to query a table: SELECT  FROM `dtc-de-375211.trips_data_all.green_tripdata` LIMIT 1000
      database: dtc-de-375211 
      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: green_tripdata
        - name: yellow_tripdata

